name: probe-override-img
description: docker:// image action
runs:
  using: docker
  image: docker://alpine:3.19
  pre-entrypoint: /bin/cat
  entrypoint: /bin/cat
  post-entrypoint: /bin/cat
  args: ["/etc/alpine-release"]
